- name: Check that exactly one subnet matching the ident exists  # noqa:no-changed-when
  ansible.builtin.command: >-
    openstack subnet show {{ subnet_name_or_id }} -f json
  register: subnet_show_cmd_raw

- name: Unmarshal output from JSON
  ansible.builtin.set_fact:
    subnet_show_cmd_result: "{{ subnet_show_cmd_raw.stdout | from_json }}"

- name: Destroy subnet  # noqa:no-changed-when
  ansible.builtin.command: >-
    openstack subnet delete {{ subnet_show_cmd_result.id }}
