extends: default
rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  hyphens:
    max-spaces-after: 4
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
