---
- name: Teardown a hosted control plane cluster from a ClusterOrder
  hosts: localhost
  gather_facts: false
  environment:
    OS_CLOUD: "{{ openstack_cloud_name|default('devstack') }}"

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  pre_tasks:
    - name: Extract template info
      ansible.builtin.include_role:
        name: extract_template_info

  tasks:
    - name: Determine working namespace
      ansible.builtin.include_role:
        name: cluster_working_namespace

    - name: Call the selected template
      ansible.builtin.include_role:
        name: "{{ template_id }}"
      vars:
        cluster_template_state: absent
