---
- name: Teardown a hosted control plane cluster from a ClusterOrder
  hosts: localhost
  gather_facts: false

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  pre_tasks:
    - name: Apply default settings
      ansible.builtin.include_role:
        name: cloudkit.service.vm_settings

    - name: Extract template info
      ansible.builtin.include_role:
        name: cloudkit.service.extract_template_info

  tasks:
    - name: Call the selected template
      ansible.builtin.include_role:
        name: "{{ template_id }}"
        tasks_from: "delete"
