---
- name: Teardown a hosted control plane cluster from a ClusterOrder
  hosts: localhost
  gather_facts: false
  environment:
    OS_CLOUD: "{{ openstack_cloud_name|default('devstack') }}"

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  pre_tasks:
    - name: Apply default settings
      ansible.builtin.include_role:
        name: cloudkit.service.cluster_settings

    - name: Extract template info
      ansible.builtin.include_role:
        name: cloudkit.service.extract_template_info

    - name: Determine working namespace
      ansible.builtin.include_role:
        name: cloudkit.service.cluster_working_namespace
      vars:
        cluster_working_namespace_cluster_order_name: "{{ cluster_order.metadata.name }}"

  tasks:
    - name: Call the selected template
      ansible.builtin.include_role:
        name: "{{ template_id }}"
        tasks_from: "delete"
