---
- name: Create a hosted control plane cluster from a ClusterOrder
  hosts: localhost
  gather_facts: false
  environment:
    OS_CLOUD: "{{ openstack_cloud_name|default('devstack') }}"

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  roles:
    - role: cluster_working_namespace
      cluster_working_namespace_cluster_order_name: "{{ cluster_order.metadata.name }}"

    - role: cluster_settings
      cluster_settings_template_id: "{{ cluster_order.spec.templateID }}"
      cluster_settings_template_parameters: "{{ cluster_order.spec.templateParameters | from_json }}"

    - role: hosted_cluster
      hosted_cluster_name: "{{ cluster_order.metadata.name }}"
      hosted_cluster_namespace: "{{ cluster_working_namespace_result }}"
      hosted_cluster_settings: "{{ cluster_settings_result }}"
      hosted_cluster_state: present

    - role: infrastructure_api
      hosted_cluster_name: "{{ cluster_order.metadata.name }}"
      hosted_cluster_namespace: "{{ cluster_working_namespace_result }}"
      hosted_cluster_settings: "{{ cluster_settings_result }}"
      hosted_cluster_state: present
      infrastructure_api_dns_ttl: "{{ dns_ttl }}"

    - role: infrastructure_ingress
      hosted_cluster_name: "{{ cluster_order.metadata.name }}"
      hosted_cluster_namespace: "{{ cluster_working_namespace_result }}"
      hosted_cluster_settings: "{{ cluster_settings_result }}"
      hosted_cluster_state: present
      infrastructure_ingress_dns_ttl: "{{ dns_ttl }}"
