---
- name: Cloudkit hosted cluster post-install configuration
  hosts: localhost
  connection: local
  gather_facts: false

  environment:
    KUBECONFIG: "{{ admin_kubeconfig | cloudkit.service.to_temp_file }}"

  vars:
    cluster_order: "{{ ansible_eda.event.payload }}"

  pre_tasks:
    - name: Extract template info
      ansible.builtin.include_role:
        name: extract_template_info

  tasks:
    - name: Post-install hosted cluster configuration
      ansible.builtin.include_role:
        name: "{{ template_id }}"
        tasks_from: post_install.yaml
