[project]
name = "cloudkit-aap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.4.0",
    "kubernetes>=32.0.1",
    "python-esiclient>=1.1.0",
    "python-esileapclient>=1.0.0",
    "python-ironicclient>=5.10.0",
    "python-openstackclient>=6.0.1",
]
