- name: Create port forwarding  # noqa:no-changed-when
  when: ports
  ansible.builtin.command: >-
    openstack esi port forwarding create {{ internal_ip }} {{ floating_ip }}
      --internal-ip-network "{{ internal_network }}"
      {% for portarg in ports %}-p {{ portarg }} {% endfor %}
      -d "{{ description }}" -f json
  register: create_port_fwd_result

- name: Show port forwarding result
  debug:
    var: create_port_fwd_result
