- name: Import nodes as agents
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Assert that node_names exists and not empty
      ansible.builtin.assert:
        that:
          - node_names is defined
          - node_names | length > 0

    - name: Import agents
      ansible.builtin.include_role:
        name: massopencloud.esi.agent
      vars:
        agent_state: present
