- name: Discover and publish templates to fulfillment service
  hosts: localhost
  gather_facts: false
  vars:
    publish_templates_namespace_default: "{{ lookup('env', 'CLOUDKIT_PUBLISH_TEMPLATES_NAMESPACE_DEFAULT') }}"
    publish_templates_namespace: "{{ lookup('env', 'CLOUDKIT_PUBLISH_TEMPLATES_NAMESPACE') | default(publish_templates_namespace_default, true) }}"
    publish_templates_service_account: "{{ lookup('env', 'CLOUDKIT_PUBLISH_TEMPLATES_SERVICE_ACCOUNT', default='template-publisher') }}"
    cloudkit_fulfillment_service_uri: "{{ lookup('env', 'CLOUDKIT_FULFILLMENT_SERVICE_URI', default='http://fulfillment-api') }}"
    cloudkit_template_collections: "{{ lookup('env', 'CLOUDKIT_TEMPLATE_COLLECTIONS') | default('cloudkit.templates', true) | split(',') }}"
  tasks:
  - name: Get client token
    ansible.builtin.command:
      cmd: >
        oc create token -n {{ publish_templates_namespace }}
        {{ publish_templates_service_account }}
        --duration=10m
    register: fulfillment_service_client_token
    changed_when: false

  - name: Discover templates
    ansible.builtin.include_role:
      name: cloudkit.service.enumerate_templates

  - name: Publish templates
    ansible.builtin.include_role:
      name: cloudkit.service.publish_templates
    vars:
      cloudkit_fulfillment_service_token: "{{ fulfillment_service_client_token.stdout }}"
