- name: Discover and publish templates to fulfillment service
  hosts: localhost
  gather_facts: false
  vars:
    publish_templates_service_account: "{{ lookup('env', 'CLOUDKIT_PUBLISH_TEMPLATES_SERVICE_ACCOUNT') }}"
    publish_templates_namespace: "{{ lookup('env', 'CLOUDKIT_PUBLISH_TEMPLATES_NAMESPACE') }}"
  tasks:
  - name: Get client token
    ansible.builtin.command:
      cmd: >
        oc create token -n {{ publish_templates_namespace }}
        {{ publish_templates_service_account }}
        --duration=10m
    register: innabox_client_token
    changed_when: false

  - name: Discover templates
    ansible.builtin.include_role:
      name: cloudkit.service.enumerate_templates

  - name: Publish templates
    ansible.builtin.include_role:
      name: cloudkit.service.publish_templates
    vars:
      cloudkit_fulfillment_service_token: "{{ innabox_client_token.stdout }}"
