- name: Display node names that will be removed from being agents
  ansible.builtin.debug:
    var: manage_agents_node_names

- name: Get list of existing agents
  kubernetes.core.k8s_info:
    kind: Agent
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ manage_agents_namespace }}"
  register: initial_agents

- name: Get list of node info
  ansible.builtin.include_role:
    name: massopencloud.esi.node
    tasks_from: list_nodes
  vars:
    node_names: "{{ manage_agents_node_names }}"
# registers: node_info_list

- name: Find matching agents
  ansible.builtin.include_role:
    name: massopencloud.esi.node
    tasks_from: get_agent_names
# registers: agents
# registers: agent_names
# registers: agent_hostnames

- name: Display matching agents
  when: agent_names is defined
  ansible.builtin.debug:
    msg:
      - "matching agent names: {{ agent_names }}"
      - "matching agent hostnames: {{ agent_hostnames }}"

- name: Delete agents
  when:
    - agent_names is defined
    - agent_names | length > 0
  kubernetes.core.k8s:
    kind: Agent
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ manage_agents_namespace }}"
    name: "{{ agent }}"
    state: absent
  loop: "{{ agent_names }}"
  loop_control:
    loop_var: agent

- name: Clean nodes
  when:
    - agent_hostnames is defined
    - agent_hostnames | length > 0
  ansible.builtin.include_role:
    name: massopencloud.esi.node
    tasks_from: clean_nodes
  vars:
    node_names: "{{ agent_hostnames | upper }}"
