- name: Get nodes
  ansible.builtin.include_role:
    name: massopencloud.esi.node
    tasks_from: get_nodes
  vars:
    node_filter_names: "{{ node_names }}"
# set_fact: node_info_list

- name: Undeploy nodes
  openstack.cloud.baremetal_node_action:
    name: "{{ node_info.name }}"
    state: absent
    deploy: false
    wait: false
  loop: "{{ node_info_list }}"
  loop_control:
    loop_var: node_info
    label: "{{ node_info.name }}"

- name: Wait for nodes to become available
  when: wait
  openstack.cloud.baremetal_node_info:
    name: "{{ node_info.name }}"
  register: node_result
  until: node_result.baremetal_nodes[0].provision_state == "available"
  retries: 300
  delay: 10
  loop: "{{ node_info_list }}"
  loop_control:
    loop_var: node_info
    label: "{{ node_info.name }}"
