- name: Provision from node_names
  when: node_names | length > 0
  block:
    - name: Get combined node and port info
      ansible.builtin.include_role:
        name: massopencloud.esi.node
        tasks_from: get_nodes
      vars:
        node_filter_names: "{{ node_names }}"
    # set_fact: node_info_list

    - name: Filter nodes that are not agents
      ansible.builtin.set_fact:
        filtered_node_info: "{{ filtered_node_info | default([]) + [node_info] }}"
      loop: "{{ node_info_list }}"
      loop_control:
        loop_var: node_info
        label: "{{ node_info.name }}"
      when: not node_info.ports | map(attribute='address') | massopencloud.esi.match_agent_addresses(node_all_agents)

    - name: Provision nodes
      when:
        - filtered_node_info is defined
        - filtered_node_info | length > 0
      block:
        - name: Set nodes to provisioning network
          ansible.builtin.include_role:
            name: massopencloud.esi.l2
            tasks_from: set_networks_for_node
          vars:
            networks:
              - "{{ node_provisioning_network_name }}"
            node: "{{ node_info.name }}"
          loop: "{{ filtered_node_info }}"
          loop_control:
            loop_var: node_info
            label: "{{ node_info.name }}"

        - name: Set deploy interface, set boot image url, and deploy nodes
          openstack.cloud.baremetal_node_action:
            name: "{{ node_info.name }}"
            instance_info:
              deploy_interface: ramdisk
              boot_iso: "{{ node_discovery_url }}"
            deploy: true
            wait: false
          loop: "{{ filtered_node_info }}"
          loop_control:
            loop_var: node_info
            label: "{{ node_info.name }}"
          when:
            - node_info.provision_state == 'available'

        - name: Wait for nodes to be deployed
          when: wait
          kubernetes.core.k8s_info:
            kind: Agent
            api_version: agent-install.openshift.io/v1beta1
            namespace: "{{ node_agent_namespace }}"
          register: node_all_agents
          until: >
            node_info.ports |
            map(attribute='address') |
            massopencloud.esi.match_agent_addresses(node_all_agents.resources) is not none
          retries: 90
          delay: 10
          loop: "{{ filtered_node_info }}"
          loop_control:
            loop_var: node_info
            label: "{{ node_info.name }}"
