- name: Get combined node and port info
  ansible.builtin.include_role:
    name: massopencloud.esi.node
    tasks_from: get_nodes
  vars:
    node_filter_names: "{{ node_names }}"
# set_fact: node_info_list

- name: Delete agents
  kubernetes.core.k8s:
    kind: Agent
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ node_agent_namespace }}"
    name: >-
      {{
        node_info.ports |
        map(attribute='address') |
        massopencloud.esi.match_agent_addresses(node_all_agents)
      }}
    state: absent
  loop: "{{ node_info_list }}"
  loop_control:
    loop_var: node_info
    label: "{{ node_info.name }}"
