- name: Create hosted cluster
  ansible.builtin.import_role:
    name: hosted_cluster
  vars:
    hosted_cluster_name: "{{ cluster_order.metadata.name }}"
    hosted_cluster_namespace: "{{ cluster_working_namespace }}"
    hosted_cluster_settings:
      ocp_release_image: "{{ ocp_release_image }}"
      pull_secret: "{{ template_parameters.pull_secret }}"
      ssh_public_key: "{{ template_parameters.ssh_public_key }}"
    hosted_cluster_node_requests: "{{ cluster_order.spec.nodeRequests }}"
    hosted_cluster_state: present

- name: Create cluster infrastructure
  ansible.builtin.import_role:
    name: cluster_infra
  vars:
    cluster_infra_state: present
    cluster_infra_name: "{{ cluster_order.metadata.name }}"
    cluster_infra_namespace: "{{ cluster_working_namespace }}"
    cluster_infra_node_requests: "{{ cluster_order.spec.nodeRequests }}"

- name: Configure port forwarding
  ansible.builtin.import_role:
    name: external_access
  vars:
    external_access_name: "{{ cluster_order.metadata.name }}"
    external_access_state: present
    external_access_namespace: "{{ cluster_working_namespace }}"
    external_access_ingress_internal_network: "network-{{ cluster_order.metadata.name }}"
