- ansible.builtin.import_role:
    name: hosted_cluster
  vars:
    hosted_cluster_name: "{{ cluster_order.metadata.name }}"
    hosted_cluster_namespace: "{{ cluster_working_namespace }}"
    hosted_cluster_settings:
      ocp_release_image: "{{ ocp_release_image }}"
      pull_secret: "{{ template_parameters.pull_secret }}"
      ssh_public_key: "{{ template_parameters.ssh_public_key }}"
    hosted_cluster_node_count: >-
      {{ cluster_order.spec.nodeRequests | map(attribute="numberOfNodes") | sum }}
    hosted_cluster_state: present

- ansible.builtin.import_role:
    name: external_access
  vars:
    external_access_name: "{{ cluster_order.metadata.name }}"
    external_access_state: present
    external_access_namespace: "{{ cluster_working_namespace }}"
