argument_specs:
  main:
    options:
      floating_ip_state:
        type: "str"
        required: true
        choices:
        - present
        - absent
      floating_ip_name:
        type: "str"
        required: true
