---
- name: Manage Secret resource containing pull-secret
  kubernetes.core.k8s:
    state: "{{ hosted_cluster_state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "pullsecret-cluster-{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ hosted_cluster_default_cluster_order_label }}"
      data:
        .dockerconfigjson: "{{ hosted_cluster_settings.pull_secret | to_json | b64encode }}"
      type: kubernetes.io/dockerconfigjson
  no_log: true

- name: Manage Secret resource containing ssh-key
  kubernetes.core.k8s:
    state: "{{ hosted_cluster_state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "sshkey-cluster-{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ hosted_cluster_default_cluster_order_label }}"
      data:
        id_rsa.pub: "{{ hosted_cluster_settings.ssh_public_key | b64encode }}"

- name: Manage HostedCluster resource
  kubernetes.core.k8s:
    state: "{{ hosted_cluster_state }}"
    definition:
      apiVersion: hypershift.openshift.io/v1beta1
      kind: HostedCluster
      metadata:
        name: "{{ hosted_cluster_name }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ {'cluster.open-cluster-management.io/clusterset': 'default'} | combine(hosted_cluster_default_cluster_order_label) }}"
      spec:
        release:
          image: "{{ ocp_release_image }}"
        pullSecret:
          name: "pullsecret-cluster-{{ hosted_cluster_name }}"
        sshKey:
          name: "sshkey-cluster-{{ hosted_cluster_name }}"
        networking:
          clusterNetwork:
            - cidr: 10.132.0.0/14
          serviceNetwork:
            - cidr: 172.31.0.0/16
        platform:
          type: Agent
          agent:
            agentNamespace: "{{ hosted_cluster_default_agent_namespace }}"
        dns:
          baseDomain: "{{ hosted_cluster_base_domain }}"
        infraID: "{{ hosted_cluster_name }}"
        services:
          - service: APIServer
            servicePublishingStrategy:
              type: LoadBalancer
              loadBalancer:
                hostname: "api.{{ hosted_cluster_name }}.{{ hosted_cluster_base_domain }}"
          - service: OAuthServer
            servicePublishingStrategy:
              type: Route
          - service: OIDC
            servicePublishingStrategy:
              type: Route
          - service: Konnectivity
            servicePublishingStrategy:
              type: Route
          - service: Ignition
            servicePublishingStrategy:
              type: Route
        controllerAvailabilityPolicy: HighlyAvailable
        infrastructureAvailabilityPolicy: HighlyAvailable
        olmCatalogPlacement: management

- name: Manage NodePool resources
  kubernetes.core.k8s:
    state: "{{ hosted_cluster_state }}"
    definition:
      apiVersion: hypershift.openshift.io/v1beta1
      kind: NodePool
      metadata:
        name: "nodepool-{{ hosted_cluster_name }}-{{ item.resourceClass }}"
        namespace: "{{ hosted_cluster_namespace }}"
        labels: "{{ hosted_cluster_default_cluster_order_label }}"
      spec:
        clusterName: "{{ hosted_cluster_name }}"
        replicas: "{{ item.numberOfNodes | int }}"
        management:
          autoRepair: false
          upgradeType: InPlace
        platform:
          type: Agent
          agent:
            agentLabelSelector:
              matchLabels: "{{ {esi_agent_resource_class_label: item.resourceClass} | combine(hosted_cluster_default_cluster_order_label) }}"
        release:
          image: "{{ ocp_release_image }}"
  loop: "{{ hosted_cluster_node_requests }}"
  loop_control:
    label: "Manage NodePool nodepool-{{ hosted_cluster_name }}-{{ item.resourceClass }}"

- name: Create cluster network
  ansible.builtin.include_role:
    name: massopencloud.esi.network
  vars:
    network_suffix: "{{ hosted_cluster_name }}"
    network_state: "{{ hosted_cluster_state }}"
  when: hosted_cluster_state == "present"

- name: Select and label new Agents resources
  ansible.builtin.include_role:
    name: manage_agents
    tasks_from: select_and_label_new_agents
  vars:
    manage_agents_cluster_order_name: "{{ hosted_cluster_name }}"
    manage_agents_desired_count: "{{ item.numberOfNodes | int }}"
    manage_agents_resource_class: "{{ item.resourceClass }}"
  loop: "{{ hosted_cluster_node_requests }}"

- name: Attach agents to cluster network and approve them
  ansible.builtin.include_role:
    name: manage_agents
    tasks_from: attach_and_approve_all_new_agents
  vars:
    manage_agents_cluster_order_name: "{{ hosted_cluster_name }}"
    manage_agents_cluster_network: "{{ create_network_result|default(omit) }}"

- name: Wait for the Agents to be removed from the cluster
  ansible.builtin.include_role:
    name: manage_agents
    tasks_from: wait_for_agents_to_be_removed
  vars:
    manage_agents_cluster_order_name: "{{ hosted_cluster_name }}"
    manage_agents_desired_count: "{{ item.numberOfNodes | int }}"
    manage_agents_resource_class: "{{ item.resourceClass }}"
  loop: "{{ hosted_cluster_node_requests }}"

- name: Approve agents assigned to the hosted cluster
  ansible.builtin.include_role:
    name: manage_agents
    tasks_from: attach_and_approve_all_new_agents
  vars:
    manage_agents_cluster_order_name: "{{ hosted_cluster_name }}"
    manage_agents_cluster_network: "{{ create_network_result|default(omit) }}"

- name: Detach agents from cluster
  ansible.builtin.include_role:
    name: manage_agents
    tasks_from: detach_and_unlabel_all_removed_agents
  vars:
    manage_agents_cluster_order_name: "{{ hosted_cluster_name }}"
    manage_agents_cluster_network: "{{ create_network_result|default(omit) }}"

- name: Delete cluster network
  ansible.builtin.include_role:
    name: massopencloud.esi.network
  vars:
    network_suffix: "{{ hosted_cluster_name }}"
    network_state: "{{ hosted_cluster_state }}"
  when: hosted_cluster_state == "absent"
