version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9@sha256:9e94b335b66993881a6fd8331050178049eec92475b68dfad8379d2168bcbf77

dependencies:
  galaxy: requirements.yaml
  python: requirements.txt
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner

options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: openshift-clients.rpm
    dest: rpms

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y install bash-completion python3-netifaces
    # COPY _build/rpms/*.rpm /tmp/
    # RUN rpm -ivh /tmp/openshift-clients.rpm
