- name: Get list of existing agents
  kubernetes.core.k8s_info:
    kind: Agent
    api_version: agent-install.openshift.io/v1beta1
    namespace: "{{ agent_namespace }}"
  register: esi_initial_agents

- name: Show number of initial number agents
  ansible.builtin.debug:
    msg:
      - "current number of agents: {{ esi_initial_agents.resources | length }}"
      - "desired number of agents: {{ desired_number_of_agents }}"

- name: Import nodes to be agents in the hostpool
  when: esi_initial_agents.resources | length < desired_number_of_agents
  block:
    - name: Get nodes list
      openstack.cloud.baremetal_node_info:
      register: all_nodes

    - name: Extract available nodes
      ansible.builtin.set_fact:
        available_node_names: >-
          {{
            all_nodes.baremetal_nodes |
            selectattr('provision_state', 'equalto', 'available') |
            map(attribute='name') |
            list
          }}

    - name: Show the number of available nodes
      ansible.builtin.debug:
        msg:
          - "number of available nodes: {{ available_node_names | length }}"

    - name: Assert there is enough available nodes
      ansible.builtin.assert:
        that:
          - available_node_names | length >= desired_number_of_agents - esi_initial_agents.resources | length
        quiet: true

    - name: Truncate list
      ansible.builtin.set_fact:
        node_names: "{{ available_node_names[:(desired_number_of_agents - esi_initial_agents.resources | length)] }}"

    - name: Import nodes
      ansible.builtin.include_tasks: import_agents.yaml

- name: Remove agents from the hostpool
  when: esi_initial_agents.resources | length > desired_number_of_agents
  block:
    - name: Assert desired number of agents is not negative
      ansible.builtin.assert:
        that:
          - desired_number_of_agents > 0
        quiet: true

    - name: Extract available agents
      ansible.builtin.set_fact:
        available_agent_names: >-
          {{
            esi_initial_agents.resources |
            selectattr('status.debugInfo.state', 'equalto', 'known-unbound') |
            map(attribute='spec.hostname') |
            list |
            upper
          }}

    - name: Show the number of available agents
      ansible.builtin.debug:
        msg:
          - "number of available agents: {{ available_agent_names | length }}"

    - name: Truncate list
      ansible.builtin.set_fact:
        node_names: "{{ available_agent_names[:(esi_initial_agents.resources | length - desired_number_of_agents)] }}"

    - name: Remove agents
      ansible.builtin.include_tasks: remove_agents.yaml
