- name: Look up finalizer target
  kubernetes.core.k8s_info:
    api_version: "{{ finalizer_target.api_version }}"
    kind: "{{ finalizer_target.kind }}"
    namespace: "{{ finalizer_target.namespace }}"
    name: "{{ finalizer_target.name }}"
  register: finalizer_resources

- name: Set finalizer_target_resource variable
  ansible.builtin.set_fact:
    finalizer_target_resource: "{{ finalizer_resources.resources|first }}"

- name: "Add finalizer to {{ finalizer_target.kind }}/{{ finalizer_target.name }}"
  when: finalizer_state == "present"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: "{{ finalizer_target.api_version }}"
      kind: "{{ finalizer_target.kind }}"
      metadata:
        namespace: "{{ finalizer_target.namespace }}"
        name: "{{ finalizer_target.name }}"
        finalizers: "{{ (finalizer_target_resource.metadata.finalizers | default([])) | union([finalizer_name]) }}"

- name: "Remove finalizer from {{ finalizer_target.kind }}/{{ finalizer_target.name }}"
  when: finalizer_state == "absent"
  kubernetes.core.k8s:
    state: present
    apply: true
    definition:
      apiVersion: "{{ finalizer_target.api_version }}"
      kind: "{{ finalizer_target.kind }}"
      metadata:
        namespace: "{{ finalizer_target.namespace }}"
        name: "{{ finalizer_target.name }}"
        finalizers: "{{ finalizer_list | default(none, true) }}"
  vars:
    finalizer_list: "{{ (finalizer_target_resource.metadata.finalizers | default([])) | difference([finalizer_name]) }}"
