---
argument_specs:
  configure_metallb_ingress:
    options:
      metallb_ingress_admin_kubeconfig:
        type: str
        required: true
      metallb_ingress_ip:
        type: str
        required: true
