---
- name: Create github oauth secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ admin_kubeconfig }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: github-oauth-secret
        namespace: openshift-config
      data:
        clientSecret: "{{ template_parameters.github_client_secret | b64encode }}"

- name: Patch oauth
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ admin_kubeconfig }}"
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: github
          type: GitHub
          mappingMethod: "{{ template_parameters.github_mapping_method|default(default_github_mapping_method) }}"
          github:
            clientID: "{{ template_parameters.github_client_id }}"
            clientSecret:
              name: "github-oauth-secret"
            teams: "{{ template_parameters.github_teams|default([]) }}"
            organizations: "{{ template_parameters.github_organizations|default([]) }}"
