- name: Check that exactly one network matching the ident exists  # noqa:no-changed-when
  ansible.builtin.command: >-
    openstack network show {{ 'network-' + network_suffix }} -f json
  register: network_show_cmd_raw

- name: Unmarshal output from JSON
  ansible.builtin.set_fact:
    network_show_cmd_result: "{{ network_show_cmd_raw.stdout | from_json }}"

- name: Destroy related router
  ansible.builtin.include_role:
    name: massopencloud.esi.l3
    tasks_from: destroy_router
  vars:
    router_name: "{{ 'router-' + network_suffix }}"

- name: Get related subnets
  openstack.cloud.subnets_info:
    filters:
      network_id: "{{ network_show_cmd_result.id }}"
  register: subnets

- name: Destroy related subnets
  ansible.builtin.include_role:
    name: massopencloud.esi.l3
    tasks_from: destroy_subnet
  vars:
    subnet_name: "{{ item.id }}"
  loop: "{{ subnets.subnets }}"

- name: Destroy network
  ansible.builtin.include_role:
    name: massopencloud.esi.l2
  vars:
    network_state: "absent"
    network_name: "{{ network_show_cmd_result.id }}"
