argument_specs:
  main:
    options:
      subnet_state:
        type: "str"
        default: present
        choices:
        - present
        - absent
      subnet_name_or_id:
        description: |
          Name of the subnet when state is `present`.
          Name or ID of subnet to be deleted when state is `absent`; the deletion will fail if the subnet name is not unique.
        type: "str"
        required: true
      network_name_or_id:
        description: |
          Name or ID of the network associated with the subnet
        type: "str"
        required: false
