- name: Check if router exists
  openstack.cloud.routers_info:
    name: "{{ router_name }}"
  register: routers

- name: Set create_router_result to found router
  when: routers.routers
  ansible.builtin.set_fact:
    create_router_result: "{{ routers.routers[0].id }}"

- name: Create a new router
  when: not routers.routers
  block:
  - name: Create router
    openstack.cloud.router:
      name: "{{ router_name }}"
      network: "{{ l3_router_external_network }}"
      interfaces: "{{ router_subnets }}"
    register: router_cmd_result

  - name: Set create_router_result to new router
    ansible.builtin.set_fact:
      create_router_result: "{{ router_cmd_result.router.id }}"
