- name: See if network is already attached to node
  block:
  - name: Check current network configuration  # noqa:no-changed-when
    ansible.builtin.command: >-
      openstack esi node network list --node {{ node }} --network {{ network }} --long
        -f json
    register: nnl_cmd_raw

  - name: Unmarshal output from JSON
    ansible.builtin.set_fact:
      nnl_result: "{{ nnl_cmd_raw.stdout | from_json }}"

- name: Attach network to node  # noqa:no-changed-when
  when: nnl_result | length == 0
  ansible.builtin.command: >-
    openstack esi node network attach --network {{ network }} {{ node }}
