- name: See if network is already attached to node
  block:
  - name: Check current network configuration  # noqa:no-changed-when
    ansible.builtin.command: >-
      openstack esi node network list --node {{ node }} --network {{ network }} --long
        -f json
    register: nnl_cmd_raw

  - name: Unmarshal output from JSON
    ansible.builtin.set_fact:
      nnl_result: "{{ nnl_cmd_raw.stdout | from_json }}"

- name: Detach network from node  # noqa:no-changed-when
  loop: "{{ nnl_result }}"
  loop_control:
    loop_var: network_info
  ansible.builtin.command: >-
    openstack esi node network detach --port {{ network_info['Network Port UUID'] }} {{ node }}

- name: Delete Neutron ports
  loop: "{{ nnl_result }}"
  loop_control:
    loop_var: network_info
  openstack.cloud.port:
    state: "absent"
    name: "{{ network_info['Network Port UUID'] }}"
