argument_specs:
  main:
    options:
      router_state:
        type: "str"
        default: present
        choices:
        - present
        - absent
      router_name_or_id:
        description: |
          Name of the router when state is `present`.
          Name or ID of router to be deleted when state is `absent`; the deletion will fail if the router name is not unique.
        type: "str"
        required: true
      router_subnets:
        description: |
          List of names or IDs of the subnets to attach to the router
        type: "list"
        required: false
