argument_specs:
  provision_nodes:
    options:
      provisioning_network_name:
        required: true
        type: str
      node_info_list:
        required: true
        type: list
        elements: dict
      discovery_url:
        required: true
        type: str
  clean_nodes:
    options:
      node_names:
        required: true
        type: list
        elements: str
  list_nodes:
    options:
      node_names:
        type: list
        elements: str
  filter_non_agent_nodes:
    options:
      node_info_list:
        required: true
        type: list
        elements: dict
  get_agent_names:
    options:
      node_info_list:
        required: true
        type: list
        elements: dict
  extract_node_location:
    options:
      node_info_list:
        required: true
        type: list
        elements: dict
      agent_topology_labels_list:
        required: true
        type: list
        elements: dict
