- name: Get kube-apiserver service
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    namespace: "{{ external_access_namespace }}-{{ external_access_name }}"
    name: kube-apiserver
  register: kube_apiserver_service

  # wait until the service exists and has a loadbalancer ip
  until: >-
    kube_apiserver_service.resources and
    kube_apiserver_service.resources[0].status.loadBalancer.ingress | default(false)
  retries: "{{ external_access_resource_wait_retries }}"
  delay: "{{ external_access_resource_wait_delay }}"

- name: Set api_internal_ip
  ansible.builtin.set_fact:
    external_access_api_internal_ip: "{{ kube_apiserver_service.resources[0].status.loadBalancer.ingress[0].ip }}"
    external_access_kube_apiserver_port: "{{ kube_apiserver_service.resources[0].spec.ports[0].port }}"

- name: Allocate api floating ip
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
  vars:
    floating_ip_state: present
    floating_ip_name: "{{ external_access_name }}-api"  # noqa:var-naming[no-role-prefix]

- name: Set api_floating_ip
  ansible.builtin.set_fact:
    external_access_api_floating_ip: "{{ allocate_floating_ip_result }}"

- name: Create port forwarding for api endpoint  # noqa:no-changed-when
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
    tasks_from: create_port_forwarding
  vars:
    internal_ip: "{{ external_access_api_internal_ip }}"
    floating_ip: "{{ external_access_api_floating_ip }}"
    internal_network: "{{ external_access_api_internal_network }}"
    ports:
    - "{{ external_access_kube_apiserver_port }}"
    description: "{{ external_access_name }}-api"

- name: Create api dns records
  when: >-
    external_access_base_domain in external_access_supported_base_domains|default([])
  amazon.aws.route53:
    state: present
    zone: "{{ external_access_base_domain }}"
    record: "{{ item }}"
    type: A
    ttl: "{{ external_access_dns_ttl }}"
    value: "{{ external_access_api_floating_ip }}"
    wait: true
    overwrite: true
  loop:
  - "api.{{ external_access_name }}.{{ external_access_base_domain }}"
  - "api-int.{{ external_access_name }}.{{ external_access_base_domain }}"

- name: Wait until agents are available
  kubernetes.core.k8s_info:
    api_version: agent-install.openshift.io/v1beta1
    kind: Agent

    namespace: "{{ external_access_agent_namespace }}"
    label_selectors:
    - "cloudkit.openshift.io/clusterorder={{ external_access_name }}"
  register: agents

  # wait until agents are assigned to the cluster
  until: agents.resources
  retries: "{{ external_access_resource_wait_retries }}"
  delay: "{{ external_access_resource_wait_delay }}"

- name: Get esi node name of an agent
  ansible.builtin.set_fact:
    external_access_worker_node_name: >-
      {{
      agents.resources[0].spec.hostname
      }}

- name: Get network details from esi  # noqa:no-changed-when
  ansible.builtin.include_role:
    name: massopencloud.esi.network
    tasks_from: get_node_network_info
  vars:
    node: "{{ external_access_worker_node_name }}"
    network: "{{ external_access_ingress_internal_network }}"

- name: Get worker node address
  ansible.builtin.set_fact:
    external_access_worker_node_ip: >-
      {{
        (node_network_info.stdout|from_json)[0]['Fixed IP']
      }}

- name: Show discovered address
  ansible.builtin.debug:
    msg: "Found address {{ external_access_worker_node_ip }} for node {{ external_access_worker_node_name }}"

- name: Allocate ingress floating ip
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
  vars:
    floating_ip_state: present
    floating_ip_name: "{{ external_access_name }}-ingress"  # noqa:var-naming[no-role-prefix]

- name: Set external_access_ingress_floating_ip
  ansible.builtin.set_fact:
    external_access_ingress_floating_ip: "{{ allocate_floating_ip_result }}"

- name: Create port forwarding for ingress endpoint  # noqa:no-changed-when
  ansible.builtin.include_role:
    name: massopencloud.esi.floating_ip
    tasks_from: create_port_forwarding
  vars:
    internal_ip: "{{ external_access_worker_node_ip }}"
    floating_ip: "{{ external_access_ingress_floating_ip }}"
    internal_network: "{{ external_access_ingress_internal_network }}"
    ports:
    - "80"
    - "443"
    description: "{{ external_access_name }}-ingress"

- name: Create ingress dns record
  amazon.aws.route53:
    state: present
    zone: "{{ external_access_base_domain }}"
    record: "*.apps.{{ external_access_name }}.{{ external_access_base_domain }}"
    type: A
    ttl: "{{ external_access_dns_ttl }}"
    value: "{{ external_access_ingress_floating_ip }}"
    wait: true
    overwrite: true
