- name: Create infrastructure for external access
  when: external_access_state == 'present'
  ansible.builtin.include_tasks: create_external_access.yaml

- name: Destroy infrastructure for external access
  when: external_access_state == 'absent'
  ansible.builtin.include_tasks: destroy_external_access.yaml
